language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.12.x
go_import_path: github.com/majidbigdeli/iwinNeffos
env:
 global:
   - GO111MODULE=on
   - CODECOV_TOKEN="6d55c2c1-e2e0-4263-8a27-8d9be84f747a"
install:
  - go get ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
